READS = ["p1_DM_H3K4_boeckel_R1"]
INPUTREADS=["p1_DM_input_boeckel_R1"]
genome="/media/ATLAS_Genomes_Annotations/human/GRCH38/primary_assembly/star_index"

rule all:
	input: expand("Annotations/{read}_Annotation.txt", read=READS)

rule fastqc:
	input: "{reads}.fastq"
	output: "FastQCfiles/{reads}_fastqc/fastqc_data.txt"
	shell: "fastqc -o FastQCfiles {input} --extract"

rule readMapping:
	input: a=expand("{reads}.fastq", reads=READS+INPUTREADS),
		   b=expand("FastQCfiles/{reads}_fastqc/fastqc_data.txt",reads=READS+INPUTREADS), 
		   c=genome
	output: expand("{reads}_mapped/Aligned.out.sam", reads=READS+INPUTREADS)
	run:
		for i in input.b:
			with open(i) as filetoread:
				lines=filetoread.readlines()
				for j in range(len(lines)):
					if re.search('>>Sequence Length Distribution',lines[j]):
						s=re.split('\s+', lines[j])
						k=input.a[input.b.index(i)]
						if s[3]=="fail":
							shell("homerTools trim " + k)
							shell("STAR --readFilesIn " + k + ".trimmed --genomeDir {input.c} --outFileNamePrefix " + k.replace(".fastq","_mapped/"))
						else:
							shell("STAR --readFilesIn " + k + " --genomeDir {input.c} --outFileNamePrefix " + k.replace(".fastq","_mapped/"))

rule makeTagDir:
	input: expand("{reads}_mapped/Aligned.out.sam", reads=READS+INPUTREADS)
	output: expand("{reads}Tags", reads=READS+INPUTREADS)
	run:
		for i in input:
			j= output[input.index(i)]
			shell("makeTagDirectory " + str(j) + " " + str(i))

rule peakCalling:
	input: expand("{read}Tags", read=READS),expand("{inputread}Tags", inputread=INPUTREADS)
	output: "Peaks/{read}_Peaks.txt"
	shell: "findPeaks {input[0]} -style factor -o {output} -i {input[1]}"

rule annotatePeaks:
	input: "Peaks/{read}_Peaks.txt"
	output: "Annotations/{read}_Annotation.txt"
	shell: """
		   pos2bed.pl {input} > Peaks/{wildcards.read}_Peaks.bed
		   awk 'BEGIN{{OFS="\t";FS="\t"}}{{print "chr"$0}}' Peaks/{wildcards.read}_Peaks.bed > Peaks/{wildcards.read}_Peaks.chr.bed
		   annotatePeaks.pl Peaks/{wildcards.read}_Peaks.chr.bed hg38 -annStats "Annotations/{wildcards.read}_AnnStats.txt" > "Annotations/{wildcards.read}_Annotation.txt" 
		   """

